# Generated by Django 2.2.8 on 2019-12-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_doctor_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.Hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_picture/'),
        ),
    ]
